---

- name: APT | Install DotDeb key
  apt_key: url='http://www.dotdeb.org/dotdeb.gpg' state=present

- name: APT | Add Dotdeb repository
  apt_repository: >
    repo='deb http://{{ dotdeb_apt_host }} {{ ansible_distribution_release }} all'
    state=present

- name: APT | Add Dotdeb repository (src)
  apt_repository: >
    repo='deb-src http://{{ dotdeb_apt_host }} {{ ansible_distribution_release }} all'
    state="{{ 'present' if dotdeb_apt_src else 'absent' }}"

- block:
    - name: SHELL | Check if openssl 1.0.2+ is available (from backports)
      shell: LANG=C apt-cache policy openssl | awk '/~bpo/ { print $1 }' | head -n 1
      register: s
      changed_when: false

    - name: APT | Add Dotdeb repository (Nginx HTTP2)
      apt_repository: >
        repo='deb http://{{ dotdeb_apt_host }} jessie-nginx-http2 all'
        state="{{ 'present' if s.stdout != '' and s.stdout | version_compare('1.0.2', 'ge') else 'absent' }}"

  when: ansible_distribution_release == "jessie"

- block:
  - name: Wheezy PHP 5.5
    include: wheezy_php55.yml
    when: dotdeb_wheezy_php_version == '5.5'

  - name: Wheezy PHP 5.6
    include: wheezy_php56.yml
    when: dotdeb_wheezy_php_version == '5.6'
  when: >
    ansible_distribution_release == "wheezy" and
    dotdeb_wheezy_php_version is not none
