---

- name: APT | Install DotDeb key
  apt_key: url='http://www.dotdeb.org/dotdeb.gpg' state=present

- name: APT | Add Dotdeb repository
  apt_repository: >
    repo='deb http://{{ dotdeb_apt_host }} {{ ansible_distribution_release }} all'
    state=present

- name: APT | Add Dotdeb repository (src)
  apt_repository: >
    repo='deb-src http://{{ dotdeb_apt_host }} {{ ansible_distribution_release }} all'
    state="{{ 'present' if dotdeb_apt_src else 'absent' }}"

- block:
  - name: Wheezy PHP 5.5
    include: wheezy_php55.yml
    when: dotdeb_wheezy_php_version == '5.5'

  - name: Wheezy PHP 5.6
    include: wheezy_php56.yml
    when: dotdeb_wheezy_php_version == '5.6'
  when: >
    ansible_distribution_release == "wheezy" and
    dotdeb_wheezy_php_version is not none
